### ISSUE TITLE
addMetric is not a function.

### ISSUE THREAD

**Issue by Vadimledyaev** [devtodev-analytics/air-sdk#1]
Hi. The new, updated ANE v 1.12 does not work:
Seems the error happens when I try to submit a progression event:
`DevToDev.StartProgressionEvent("LEVEL " + levelID, params)  //where levelID=1, params is a new LocationEventParams`

log:
`[Fault] exception, information=TypeError: Error #1006: addMetric is not a function.`

Environment
- DTD version 1.12
- AIR SDK version: AIR v30.0.0
- Development IDE: FlashDevelop 5.3.3.51
- Development OS: Windows 10

**Comment by ghost** [comment]
Hello, on what platform does this error occur?

**Comment by Vadimledyaev** [comment]
Hi, was tested on Windows only at this moment.
Here's the error stack for you:
![image](https://user-images.githubusercontent.com/224841/41544575-24c6f204-732a-11e8-8659-f97a8fdef79a.png)

**Comment by ghost** [comment]
Thanks, we fixed this problem and plan to release version 1.12.1 tomorrow.

**Comment by ghost** [comment]
Hello, we released [v1.12.1](https://github.com/devtodev-analytics/air-sdk/releases/tag/v1.12.1), please try it
