### ISSUE TITLE
Android 64-bit

### ISSUE THREAD

**Issue by inovento** [devtodev-analytics/air-sdk#2]
Hello,

We would like to integrate the DevToDev service into our new game on Android but we can now publish on GooglePlay only if all included ANEs support the 64-bit Android platform that has been made available through Adobe/Harmann AIR SDK 33.

So far the DevToDev SDK ANE has not been updated to include the 64-bit Android code and would like to ask whether you have plans to make it available anytime in the future.

We're sure that all AIR community actively using or planning to use DevToDev in their AIR projects will highly appreciate your efforts.

Thanks!

**Comment by RinatTalibullin** [comment]
Hello!
We will look into this.

**Comment by RinatTalibullin** [comment]
Hello! 

ARM64 support was added in SDK version 1.12.5.
